name: Generate short SHA
description: 'Generate short SHA'
outputs:
  short-sha:
    description: 'The generated short SHA'
    value: ${{ steps.short-sha.outputs.short_sha }}
runs:
  using: composite
  steps:
    - id: short-sha
      shell: bash
      run: echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
