name: Generate short SHA
description: ''
outputs:
  short-sha:
    description: ''
    value: ${{ steps.short-sha.outputs.short-sha }}
runs:
  using: composite
  steps:
    - id: short-sha
      shell: bash
      run: echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
